import * as functions from "firebase-functions/v2";
import * as admin from "firebase-admin";
import { App, ExpressReceiver } from "@slack/bolt";
import { Octokit } from "@octokit/rest";

admin.initializeApp();

const receiver = new ExpressReceiver({
  signingSecret: process.env.SLACK_SIGNING_SECRET || "dummy",
  // ルートパスでリクエストを受け取れるように設定
  endpoints: "/",
  processBeforeResponse: true,
});

const app = new App({
  token: process.env.SLACK_BOT_TOKEN || "dummy",
  receiver,
});

const octokit = new Octokit({
  auth: process.env.GITHUB_TOKEN,
});

const GITHUB_OWNER = process.env.GITHUB_OWNER || "";
const GITHUB_REPO = process.env.GITHUB_REPO || "";
const GITHUB_TEMPLATE_REPO = process.env.GITHUB_TEMPLATE_REPO || "";
const SLACK_ALLOWED_CHANNEL = process.env.SLACK_ALLOWED_CHANNEL || "";

// Slack メンションの処理
app.event("app_mention", async ({ event, client, say }) => {
  // 特定のチャンネルのみで動作するように制限
  if (SLACK_ALLOWED_CHANNEL && event.channel !== SLACK_ALLOWED_CHANNEL) {
    console.log(`Ignored mention in channel ${event.channel}`);
    return;
  }

  const text = event.text.replace(/<@.*?>/, "").trim();

  if (text.includes("新しいアプリを作って")) {
    await say("新しいアプリのリポジトリ作成を開始します。");
    try {
      await createNewRepo(say);
    } catch (error) {
      console.error(error);
      await say("リポジトリの作成に失敗しました。");
    }
  } else {
    // Issue プレビューの生成
    const title = `[jules] ${text.split("\n")[0].substring(0, 50)}`;
    const fullBody = `ユーザーの指示:\n${text}\n\nGenerated by my-dev-center`;

    // Slack ボタンの value 制限 (2000文字) を考慮して本文を切り詰める
    const MAX_VALUE_LENGTH = 1500;
    const bodyForValue = fullBody.length > MAX_VALUE_LENGTH
      ? fullBody.substring(0, MAX_VALUE_LENGTH) + "..."
      : fullBody;

    await client.chat.postMessage({
      channel: event.channel,
      blocks: [
        {
          type: "section",
          text: {
            type: "mrkdwn",
            text: `*Issue プレビュー*\n\n*タイトル:* ${title}\n*本文:*\n${fullBody.substring(0, 1000)}${fullBody.length > 1000 ? "..." : ""}`,
          },
        },
        {
          type: "actions",
          elements: [
            {
              type: "button",
              text: {
                type: "plain_text",
                text: "作成",
              },
              action_id: "create_issue",
              value: JSON.stringify({ title, body: bodyForValue }),
              style: "primary",
            },
          ],
        },
      ],
    });
  }
});

// インタラクションの処理
app.action("create_issue", async ({ ack, body, client, action }) => {
  await ack();

  if (action.type !== "button" || !action.value) return;
  const { title, body: issueBody } = JSON.parse(action.value);

  try {
    const result = await octokit.issues.create({
      owner: GITHUB_OWNER || "owner-not-set",
      repo: GITHUB_REPO || "repo-not-set",
      title: title,
      body: issueBody,
      labels: ["jules"],
    });

    if (body.channel?.id) {
      await client.chat.postMessage({
        channel: body.channel.id,
        text: `Issue を作成しました: ${result.data.html_url}`,
      });
    }
  } catch (error) {
    console.error(error);
    if (body.channel?.id) {
      await client.chat.postMessage({
        channel: body.channel.id,
        text: "Issue の作成に失敗しました。",
      });
    }
  }
});

async function createNewRepo(say: any) {
  const newRepoName = `new-app-${Date.now()}`;
  const result = await octokit.repos.createUsingTemplate({
    template_owner: GITHUB_OWNER || "owner-not-set",
    template_repo: GITHUB_TEMPLATE_REPO || "template-not-set",
    owner: GITHUB_OWNER || "owner-not-set",
    name: newRepoName,
    private: true,
  });
  await say(`新しいリポジトリを作成しました: ${result.data.html_url}`);
}

export const devCenter = functions.https.onRequest(receiver.app);
