// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqJayeQ_bkY9axG87ycfEPAA8AgMfHJRw',
    appId: '1:829045167829:web:bcfff63b98f49abec8745c',
    messagingSenderId: '829045167829',
    projectId: 'pomodoro-timer-kawakita-202602',
    authDomain: 'pomodoro-timer-kawakita-202602.firebaseapp.com',
    storageBucket: 'pomodoro-timer-kawakita-202602.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWwxr57f3z6NQMvOb_kLD9383wYq4P2EQ',
    appId: '1:829045167829:android:e5290fe23fa7e05dc8745c',
    messagingSenderId: '829045167829',
    projectId: 'pomodoro-timer-kawakita-202602',
    storageBucket: 'pomodoro-timer-kawakita-202602.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcFm9zRQPaxrKTtqbCC6eNcCO9RVWwPKA',
    appId: '1:829045167829:ios:377e189b9176044fc8745c',
    messagingSenderId: '829045167829',
    projectId: 'pomodoro-timer-kawakita-202602',
    storageBucket: 'pomodoro-timer-kawakita-202602.firebasestorage.app',
    iosBundleId: 'com.example.pomodoroTimer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcFm9zRQPaxrKTtqbCC6eNcCO9RVWwPKA',
    appId: '1:829045167829:ios:d566a8015cfbde5ac8745c',
    messagingSenderId: '829045167829',
    projectId: 'pomodoro-timer-kawakita-202602',
    storageBucket: 'pomodoro-timer-kawakita-202602.firebasestorage.app',
    iosBundleId: 'com.kawakita.pomodoro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqJayeQ_bkY9axG87ycfEPAA8AgMfHJRw',
    appId: '1:829045167829:web:8ed39a965ff2637bc8745c',
    messagingSenderId: '829045167829',
    projectId: 'pomodoro-timer-kawakita-202602',
    authDomain: 'pomodoro-timer-kawakita-202602.firebaseapp.com',
    storageBucket: 'pomodoro-timer-kawakita-202602.firebasestorage.app',
  );
}
